### ISSUE TITLE
licensing under LGPL

### ISSUE THREAD

**Issue by jordens** [tass-belgium/picotcp#428] opened 2016-10-17 17:23 UTC
Thanks for the constructive discussion in #408 and for re-licensing under GPLv2/GPLv3!

While surveying the a specific implication of GPL to our user base and possible future applications/uses of ARTIQ, we feel that moving to LGPLv3+ could be appropriate for us (m-labs/artiq#570). But that move would preclude using picotcp as our networking. Picotcp is first on our list.

What are the chances of seeing picotcp move to LGPLv3 (plus or not)?

**Comment by phalox** [comment] 2016-10-18 12:18
Hi,

The matter has not been discussed internally yet, but I'll share you my personal take on the matter.

LGPL is a very difficult license for picoTCP, as picoTCP is funded by Altran and therefore needs to generate a certain return through commercial-license income. We're happy to provide picoTCP under GPL, but this means that the party using picoTCP should do the same with their code (the open source world gets better, so everyone wins). In case of LGPL, the other party is free to use this with closed sources and therefore only the other party gets better. This also means that license income would come entirely to a halt. I'm therefore very hesitant that such a change will happen anytime soon.

Of course, if you can help us out with a different business model, I'd happily take it to our management and try to convince them.

What's driving the decision for Artiq to change the license? Are you also considering to become a for-profit organisation who would want to see a return on the R&D costs you're doing?

**Comment by jordens** [comment] 2016-10-19 10:59
With picotcp LGPL one would generate income through the same commercial licenses. I would assume those licensees are distributing modified versions with other/more featues of picotcp that clearly exceed the LGPL "linking" allowance. If those customers want to continue distributing those proprietary modifications they need to continue under the same licensing terms. The LGPL would not provide them a way out. The other revenue stream is support, maintenance, adding features. Those two concepts are also our business model for ARTIQ.

ARTIQ provides an infrastructure, libraries, and a domain specific language that physicists use to write "experiments" to run their labs. The fundamental driver for ARTIQ moving to LGPL is (as outlined in the issue referenced above) that we don't want experiments to be considered derivative works of ARTIQ and have them fall under the GPL. We do encourage and expect physicists to openly publish and release their experiments as open source as this is accepted proper research practice. But we don't want to enforce it through the GPL.

**Comment by danielinux** [comment] 2016-10-19 14:40
For embedded application, LGPL would not make any difference indeed because in 99% of the cases the linking exception cannot be triggered (embedded developers tend to statically link libraries in their code, so the application code becomes a derivative of the library itself).

On the other hand, LGPL does not enforce the four freedoms when dynamically linked with other projects. Suppose that picoTCP is used as shared object to allow application to access the network via userspace TCP/IP stack, say, in a UNIX userland. In this case, non-free application would be allowed to link with (unmodified) picoTCP, but they won't classify as derivatives.

In the latter case, LGPL behaves as a permissive license (such as one of those Open Source licenses), with the only difference that it enforces redistributing modifications of the library itself.

When the technicality is worked around in the embedded world, there will be basically no reason for a picoTCP user to opt for the proprietary EULA, and the company will potentially lose the revenue from the licenses on those case where, today, a GPL is not applicable.

In my opinion, switching to LGPL will lead to no benefits at all, and might harm the current business model. I see no valid compatibility reasons to switch to LGPL, and derivatives including other LGPL libraries can still exist as GPL. 

In the case of ARTIQ, you need to clearly state that integrating TCP/IP functionalities into your libraries will change the license of the library from LGPL to GPL, meaning that they will be required to release their experiment code as Free. Whenever this is not applicable, they need to link picoTCP dynamically and purchase a separate license. In my experience, almost no scientist care about applying a specific license to their code. If they don't want to release the code as Free Software, they'll probably be not inclined to release it as Open Source either, so again the GPL legacy is a good thing...

Again, this is just my personal opinion, as I am not part of Altran anymore, but I would see switching to LGPL as a regression for the project.

**Comment by jordens** [comment] 2016-10-19 15:13
No. To use the LGPL exception you only [have to provide the object code of the application](https://www.gnu.org/licenses/gpl-faq.en.html#LGPLStaticVsDynamic) so that the user can modify the library and relink.

**Comment by jordens** [comment] 2016-10-19 15:17
And statically linked copyleft applications obviously all automatically meet that requirement.

**Comment by danielinux** [comment] 2016-10-19 15:35
Thanks for the correction. This enforces my point actually, because any user would in fact be able to publicly distribute binary-only blobs that link with picoTCP without having to pay for a license, or release their sources, with no need to work around the license either. This sounds like a horrible scenario, both for the Free Software community and the copyright holders.

**Comment by jordens** [comment] 2016-10-19 16:06
It's only "horrible" if you are abnormally proud of the viral side effect of the GPL.

It is distinctly weird to justify the fact that all open source users of picotcp are being locked into GPL, by claiming that this is the only way to make commercial licensing schemes work.
It seems like one type of user (open source projects) has to face restrictions (viral GPL) that are aimed at sustaining something completely orthogonal (commercial licensing).

**Comment by danielinux** [comment] 2016-10-19 17:20
I don't like the term viral. It's not an infection, it's about propagating freedom, which is your own right. If you can't comply with it, it means you are closing your sources (or allow other people building up closed-source product with your openly distributed code), so I am totally supportive towards my ex-employer current licensing scheme, as it is at the same time profitable and very "ecologic".

Open Source alone, with no enforced freedom, is totally pointless. If Free projects were open only, there would be no open source today. If open source users have to pay a price, they'd better consider freeing up their code. When this is not applicable, then we're again talking about business.

**Comment by danielinux** [comment] 2016-10-19 17:22
Also, I don't see how "commercial" is orthogonal to "free". The opposites of Free in terms of software are "proprietary", "hidden", "shameful", and not "commercial" or "profitable". GPL itself allows commercial use altogether.

**Comment by phalox** [comment] 2016-10-19 20:44
Hi @jordens and @danielinux. This seems to be getting a heated discussion about the GPL, where you'll always have the two different factions.

Next to this fact, I'll give you a bit of insight in what our business model is to keep picoTCP sustainably developed up to industry standards (especially the latter is something that costs money).
A major part of picoTCP's income should currently come from commercial license fees. Something that the customers we work with pay happily (just count the engineering hours it costs to just integrate an existing stack you don't even know into your own projects). We can only get these licenses fees when we stick with a 'we open source, you open source license' otherwise there is indeed no commercial license that would apply. The services you mention are indeed another path that we're walking, but a decision about getting or not getting license fees is one that should not be taken lightly and is a pretty permanent one.

We chose to go open source, out of ideology but also to be transparant. Please tell me how many commercial - company maintained - stacks you know that provide their source code and give insight into code quality and test results? We believe this is crucial in the fast-moving (iot) world, so that interested parties can make the right choice. Whatever license we choose, there will always be people who won't like it. We do however regret any project that might not be able to use our stack.

Lastly, if you could guarantee an amount of incoming engineering assignments for us that would compensate for the loss of license income and would be willing to commit to a certain amount of engineering effort in picotcp as we're currently spending, then another argument could be made to management.

**Comment by jordens** [comment] 2016-10-20 12:22
I am fine with the discussion style and with @danielinux. These discussions are not emotional or personal to me.
There is no commercially backed/funded stack of similar proportions that I am aware of. This is a reason why we are so interested in picotcp. But there are lots of examples where companies develop e.g. linux kernel drivers and push big kernel infrastructural codebases in the open with tests and all the bells and whistles.
I can't really give you much advice on commercial strategy. Certainly not advice you haven't heard already.
Can I conclude that the chances for LGPL are slim at best?

**Comment by phalox** [comment] 2016-10-21 11:06
At this very moment that's indeed the right conclusion. I must admit that personally I'd love to have a stack that could be used everyone and in any project, but that's not for today just yet.

If you do decide to go through with making Artiq lgpl, I'm very curious on how you'll approach business (and its models) so we can learn from this.

PS: if we can put together an actual business case I'm still willing to take it to management and see what their response is.

**Comment by frederikvs** [comment] 2016-10-28 09:05
I think this discussion has been concluded : LGPL is not a likely option for picoTCP. If at some point, somebody believes they can bring new arguments to the table, feel free to re-open, but for now I'll close this issue.

**Closed by frederikvs** 2016-10-28 09:05 UTC
